### ISSUE TITLE
Commuter does not run on macOS

### ISSUE THREAD

**Issue by nikhilkuria** [nteract/nteract#3654]
I followed the instructions to install it 
`yarn global add @nteract/commuter` 

Afterwards, when i try to run it using 
`COMMUTER_LOCAL_STORAGE_BASEDIRECTORY=<~/dev/notebooks> commuter`

it fails with the following error
```
CONFIGURED DISCOVERY none
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module '../../babel.flow.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/nkose/.config/yarn/global/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
```

**Comment by DemonR** [comment]
I tried both npm and yarn install, they all produce the same error. It only works when starting as development version from the repo

**Comment by andriuspl** [comment]
Yes, same here.

**Comment by willingc** [comment]
Thanks folks for the reports. We will investigate this along with #3666 when contributors are available.

Development version appears to work per @DemonR.

**Comment by weldpua2008** [comment]
Same 
```
# NODE_ENV=production COMMUTER_STORAGE_BACKEND=s3 COMMUTER_BUCKET=ci /usr/local/nodejs-binary-8.15.0/bin/commuter server
CONFIGURED DISCOVERY none
module.js:550
    throw err;
    ^

Error: Cannot find module './config/babel.flow.config'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/nodejs-binary-8.15.0/lib/node_modules/@nteract/commuter/node_modules/@nteract/webpack-configurator/index.js:12:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

for:
 
```# uname -a
Linux server0a 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
# node  -v   
v8.15.0
# npm -v
6.4.1

```

**Comment by willingc** [comment]
bump @rgbkrk @captainsafia Thoughts?

**Comment by rgbkrk** [comment]
I'm going to move this issue over to nteract/commuter, I'll be working on commuter again this week and we can track it there.
